on:
  workflow_dispatch: 
  schedule:
    - cron: '*/5 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: testing github action smtp
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: ${{ secrets.SUBJECT }}
          body: ${{ secrets.BODY }}
          to: ${{ secrets.EMAIL_USER3 }}
          from: ${{ secrets.EMAIL_USER }}
